version: "3.6"

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saibaishitai_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/db/multibyte.cnf:/etc/mysql/conf.d/multibyte.cnf
    ports:
      - "13306:3306"
  web:
    build: .
    image: app:1.0.0
    tty: true
    stdin_open: true
    volumes:
      - .:/app:cached
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
      - rails_cache:/app/tmp/cache
      - packs:/app/public/packs
      - packs_test:/app/public/packs-test
    tmpfs:
      - /tmp
    environment:
      TZ: "Asia/Tokyo"
      RAILS_ENV: development
      DATABASE_URL: "mysql2://root:root@db"
      EDITOR: "vim"
      BUNDLE_PATH: "/app/vendor/bundle"
      BOOTSNAP_CACHE_DIR: "/app/vendor/bundle"
      WD_INSTALL_DIR: "/usr/local/bin"
      HISTFILE: "/app/log/.bash_history"
    depends_on:
      - db
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    expose: ["3000"]
    ports: ["3000:3000"]
    user: root
    working_dir: /app

volumes:
  mysql-data:
  bundle:
  node_modules:
  rails_cache:
  packs:
  packs_test: